apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loghoi-backend-output
  namespace: loghoihoi
  labels:
    app: loghoi
    component: backend-storage
spec:
  accessModes:
    - ReadWriteOnce  # Most CSI drivers support RWO
  # storageClassName not specified - uses default StorageClass
  resources:
    requests:
      storage: 10Gi  # ログファイル保存用に10GB

