apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data
  namespace: loghoihoi
  labels:
    app: loghoi
    component: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName not specified - uses default StorageClass
  resources:
    requests:
      storage: 10Gi



