apiVersion: apps/v1
kind: Deployment
metadata:
  name: loghoi-frontend
  namespace: loghoihoi
  labels:
    app: loghoi
    component: frontend
    version: v1.0.10
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loghoi
      component: frontend
  template:
    metadata:
      labels:
        app: loghoi
        component: frontend
        version: v1.0.32
    spec:
      containers:
      - name: frontend
        image: ghcr.io/konchangakita/loghoi-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7777
          name: http
          protocol: TCP
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        envFrom:
        - configMapRef:
            name: loghoi-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 7777
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 7777
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
          readOnly: true
      volumes:
      - name: nginx-config
        configMap:
          name: loghoi-nginx-config
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
