apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loghoi-ingress
  namespace: loghoi
  labels:
    app: loghoi
    component: ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    # Socket.IO用の設定（リクエストバッファリング無効化）
    traefik.ingress.kubernetes.io/buffering: "false"
spec:
  ingressClassName: kommander-traefik
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: loghoi-backend-service
            port:
              number: 7776
      - path: /socket.io
        pathType: Prefix
        backend:
          service:
            name: loghoi-backend-service
            port:
              number: 7776
      - path: /kibana
        pathType: Prefix
        backend:
          service:
            name: kibana-service
            port:
              number: 5601
      - path: /
        pathType: Prefix
        backend:
          service:
            name: loghoi-frontend-service
            port:
              number: 7777
