FROM node:20-slim 

RUN apt-get update -y
RUN apt-get install -y curl

COPY ./next-app /usr/src/next-app
WORKDIR /usr/src/next-app/loghoi
RUN yarn
#RUN npm run build

CMD ["npm", "run", "dev"]
#CMD ["npm", "start"]
#CMD ["tail", "-f", "/dev/null"]
