FROM python:3.11.4-slim

RUN apt-get update -y
RUN apt-get install -y curl
RUN apt-get install -y ssh-client
RUN pip install -U pip

WORKDIR /tmp
COPY ./requirements.txt .
RUN pip install -r requirements.txt

RUN mkdir /usr/src/output
RUN chmod 766 /usr/src/output

COPY ./flaskr /usr/src/flaskr
WORKDIR /usr/src/flaskr

CMD ["tail", "-f", "/dev/null"]
#CMD ["python", "app.py"]